### ISSUE TITLE
Figure out a data source

### ISSUE THREAD

**Issue by jdbohrman** [jdbohrman/paganfacts.io#3]
Scenario A:

Use Scrapy to scrape deity information from related wikis. 

Scenario B:

Form a dataset from scratch, which sounds like a pain in the ass but might be what has to happen.

**Comment by Goldbishop** [comment]
Downloaded the Repo....Project is referring to a Data Source that I do not have a Model available.

When will a database model script be available?

**Comment by jdbohrman** [comment]
> Downloaded the Repo....Project is referring to a Data Source that I do not have a Model available.
> 
> When will a database model script be available?

Hey John, try it now. Should be good to go.
